version: "3.8"

services:
  app:
    container_name: nextjs_app_docker
    image: derrick93/cvdocker:production
    restart: always
    ports:
      - "4001:3000"  # Expose le port 3000 du conteneur sur le port 4000 du serveur
    environment:
      - APP_ENV=production  # Remplace par tes variables d'environnement si nécessaire
