version: "3.8"

services:
  app:
    container_name: nextjs_app_docker
    image: derrick93/cvdocker:production
    restart: always
    ports:
      - "4001:3000"
    environment:
      - APP_ENV=production
      - DATABASE_URL=${DATABASE_URL}  # Ajoutez cette ligne
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}